import { RouteEngine } from './route-engine.js';
const engine=await RouteEngine.load();
const PORT_IDS=Object.values(engine.nodes).filter(n=>n.type==='port').map(n=>n.id);
const TYPES={coastal60:{name:'Coastal Ferry 60',capacity:60,speed:35,range:180,opKm:6.5,price:35000,symbol:'⛴'},swift80:{name:'HSC Aegean Swift 80',capacity:80,speed:55,range:260,opKm:9.5,price:85000,symbol:'➤'}};
const COLORS=['#173f5f','#c96c4a','#19795d','#7a5fa3','#b8860b','#2f6f8f','#8c4b62','#4f6b3a'];
const PORT_MARKET={ayvalik:{price:0,country:'TR'},kucukkuyu:{price:0,country:'TR'},cesme:{price:20000,country:'TR'},chios:{price:25000,country:'GR'},mytilene:{price:30000,country:'GR'}};
const LINE_MARKET={'ayvalik-kucukkuyu':{price:12000,origin:'ayvalik',destination:'kucukkuyu',domestic:true},'ayvalik-cesme':{price:30000,origin:'ayvalik',destination:'cesme',domestic:true},'cesme-chios':{price:15000,origin:'cesme',destination:'chios',domestic:false},'ayvalik-mytilene':{price:22000,origin:'ayvalik',destination:'mytilene',domestic:false},'chios-mytilene':{price:24000,origin:'chios',destination:'mytilene',domestic:true}};
const C={base:.72,key:'aegean-fleet-fleet-v9',old:'aegean-fleet-fleet-v8',start:new Date(2020,4,1,8),dockTax:.08,maintEvery:500,maintCost:180,startCash:2000,loadCostMax:.18};
const SUMMER_FARES={'ayvalik-kucukkuyu':16,'ayvalik-mytilene':25,'ayvalik-cesme':32,'cesme-chios':22,'chios-mytilene':34},FARE_MULT={summer:1,shoulder:.92,low:.81,winter:.72},SPEED_UPGRADES={4:{cost:30000},8:{cost:120000}};
const ports=Object.fromEntries(PORT_IDS.map(id=>[id,engine.getNode(id)])),q=id=>document.getElementById(id),route=(a,b)=>engine.getRoute({mode:'sea',origin:a,destination:b}),routeKey=(a,b)=>[a,b].sort().join('-');
function seasonBand(d){const m=d.getMonth()+1;if([6,7,8].includes(m))return['Yaz sezonu','summer',1.55];if([5,9].includes(m))return['Ara sezon','shoulder',1.15];if([4,10].includes(m))return['Sakin sezon','low',.58];return['Kış sezonu','winter',.22]}
function timeBand(d){const h=d.getHours()+d.getMinutes()/60;if(h>=7&&h<10)return['Sabah yoğunluğu',1.45];if(h>=16&&h<20)return['Akşam yoğunluğu',1.65];if(h>=23||h<7)return['Gece talebi',.18];return['Gündüz talebi',1]}
function distanceDemandFactor(km){if(km<=20)return 1.1;if(km<=50)return 1.04;if(km<=100)return .98;return .92}
function fareFor(a,b,d=now()){const base=SUMMER_FARES[routeKey(a,b)]??Math.round(18+route(a,b).distanceKm*.13);return Math.round(base*FARE_MULT[seasonBand(d)[1]])}
function newVehicle(id,type='coastal60',name='MV Ege',loc='ayvalik',colorIndex=0){return{id,type,name,loc,colorIndex,dst:null,pair:null,st:'idle',pas:0,manifest:{},p:0,fullness:80,autoTour:false,plannedDst:'',lastRevenue:0,lastOp:0,currentOp:0,kmMaint:0,totalKm:0}}
function emptyQueues(){const w={};for(const a of PORT_IDS){w[a]={};for(const b of PORT_IDS)if(a!==b)w[a][b]=0}w.ayvalik.kucukkuyu=4;w.kucukkuyu.ayvalik=3;return w}
function fresh(){return{m:0,s:1,cash:C.startCash,unlocked:['ayvalik','kucukkuyu'],openedLines:['ayvalik-kucukkuyu'],speedTiers:[1,2],vehicles:[newVehicle('v1')],selected:'v1',w:emptyQueues(),fr:{},v:9,marketTab:'vehicles'}}
let S=fresh(),markers={},shipMarkers={},routeLine=L.polyline([],{color:'#315f78',weight:3,opacity:.75,dashArray:'8 10'}),lastFrame=performance.now(),lastSaveMinute=-1,toastTimer;
const E={date:q('date'),season:q('season'),time:q('time'),cash:q('cash'),fleetPanel:q('fleetPanel'),marketPanel:q('marketPanel'),vehicleSelect:q('vehicleSelect'),status:q('status'),routeBadge:q('routeBadge'),onb:q('onb'),capacity:q('capacity'),lastRevenue:q('lastRevenue'),operation:q('operation'),maint:q('maint'),destination:q('destination'),startTrip:q('startTrip'),fareText:q('fareText'),fullness:q('fullness'),fullnessText:q('fullnessText'),autoTour:q('autoTour'),progressLabel:q('progressLabel'),goal:q('goal'),fill:q('fill'),marketCards:q('marketCards'),toast:q('toast'),reset:q('reset'),rangeBadge:q('rangeBadge')};
const map=L.map('map',{center:[39.32,26.5],zoom:9,minZoom:7,maxZoom:13,zoomControl:false,attributionControl:false});L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}{r}.png',{maxZoom:13}).addTo(map);L.control.zoom({position:'bottomleft'}).addTo(map);routeLine.addTo(map);
const vehicle=()=>S.vehicles.find(v=>v.id===S.selected)||S.vehicles[0],spec=v=>TYPES[v.type],unlocked=id=>S.unlocked.includes(id),lineLicensed=(a,b)=>S.openedLines.includes(routeKey(a,b)),routeDefined=(a,b)=>Boolean(engine.routeData?.routes?.[`${a}-${b}`]||engine.routeData?.routes?.[`${b}-${a}`]),usableDirectRoute=(a,b)=>unlocked(a)&&unlocked(b)&&routeDefined(a,b)&&lineLicensed(a,b);
function money(v){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v)}function toast(x){E.toast.textContent=x;E.toast.classList.add('s');clearTimeout(toastTimer);toastTimer=setTimeout(()=>E.toast.classList.remove('s'),3000)}function now(){return new Date(C.start.getTime()+S.m*60000)}
function findTransferPath(origin,destination){if(origin===destination)return[origin];if(usableDirectRoute(origin,destination))return[origin,destination];const available=S.unlocked.filter(id=>PORT_IDS.includes(id)),paths=[[origin]],visited=new Set([origin]);while(paths.length){const path=paths.shift(),cur=path.at(-1);for(const next of available){if(next===cur||visited.has(next)||!usableDirectRoute(cur,next))continue;const np=[...path,next];if(next===destination)return np;visited.add(next);paths.push(np)}}return null}
const nextHop=(a,b)=>findTransferPath(a,b)?.[1]||null;
function demandScore(a,b,d=now()){const path=findTransferPath(a,b);if(!path)return 0;return seasonBand(d)[2]*timeBand(d)[1]*(ports[a].intensity||.6)*distanceDemandFactor(route(path[0],path[1]).distanceKm)}
function level(v){return v>=1.25?'Çok yoğun':v>=.85?'Yoğun':v>=.5?'Normal':v>=.25?'Sakin':'Çok sakin'}function queueCount(a,b){return S.w[a]?.[b]??0}function setQueue(a,b,n){(S.w[a]??={})[b]=Math.max(0,Math.round(n))}function frac(a,b){return S.fr[`${a}:${b}`]||0}function setFrac(a,b,n){S.fr[`${a}:${b}`]=n}function target(v){return Math.ceil(spec(v).capacity*v.fullness/100)}
function portPurchaseText(id){const item=PORT_MARKET[id];if(!item||item.price===0)return'Başlangıç limanı';return`${money(item.price)} · Limanı aç`}
function portIcon(id,index){const locked=!unlocked(id),side=index%2?'l':'r';return L.divIcon({className:'',html:`<div class="ps ${side} ${locked?'locked':''}"><div class="pd"></div><div class="pc"><div class="pt">${ports[id].name}${locked?' · Kilitli':''}</div><div class="pv" id="pv-${id}"></div></div></div>`,iconSize:[18,18],iconAnchor:[9,9]})}
function openPortPopup(id){if(unlocked(id))return;const item=PORT_MARKET[id];if(!item)return;const canBuy=S.cash>=item.price,html=`<div class="port-buy-popup"><strong>${ports[id].name}</strong><div>${money(item.price)}</div><button id="buy-port-popup" ${canBuy?'':'disabled'}>${canBuy?'Limanı satın al':'Yetersiz bakiye'}</button></div>`,popup=L.popup({closeButton:true,offset:[0,-8]}).setLatLng(ports[id].terminal).setContent(html).openOn(map);setTimeout(()=>{const b=document.getElementById('buy-port-popup');if(b&&!b.disabled)b.onclick=()=>{buyPort(id);map.closePopup(popup)}},0)}
PORT_IDS.forEach((id,i)=>{const m=L.marker(ports[id].terminal,{icon:portIcon(id,i),zIndexOffset:400}).addTo(map);m.on('click',()=>openPortPopup(id));markers[id]=m});
function shipIcon(v){const t=spec(v),color=COLORS[v.colorIndex%COLORS.length];return L.divIcon({className:'',html:`<div class="sc ship-${v.type}" style="--ship-color:${color}">${t.symbol}</div>`,iconSize:[32,32],iconAnchor:[16,16]})}function addVehicleMarker(v){const m=L.marker(ports[v.loc].terminal,{icon:shipIcon(v),zIndexOffset:1000}).addTo(map).bindTooltip(v.name,{permanent:true,direction:'top',offset:[0,-16],className:'sl'});m.on('click',()=>{S.selected=v.id;showView('fleet');render()});shipMarkers[v.id]=m}function rebuildShips(){Object.values(shipMarkers).forEach(m=>m.remove());shipMarkers={};S.vehicles.forEach(addVehicleMarker)}function rebuildPortIcons(){PORT_IDS.forEach((id,i)=>markers[id].setIcon(portIcon(id,i)))}
function generate(min){const d=now();for(const a of S.unlocked)for(const b of S.unlocked){if(a===b||!findTransferPath(a,b))continue;const total=frac(a,b)+min*C.base*demandScore(a,b,d),n=Math.floor(total);if(n)setQueue(a,b,queueCount(a,b)+n);setFrac(a,b,total-n)}}
function board(v){if(v.st!=='boarding'||!v.dst)return;let free=spec(v).capacity-v.pas;const candidates=S.unlocked.filter(final=>final!==v.loc&&queueCount(v.loc,final)>0&&nextHop(v.loc,final)===v.dst).sort((a,b)=>Number(a!==v.dst)-Number(b!==v.dst));for(const final of candidates){if(free<=0)break;const n=Math.min(free,queueCount(v.loc,final));setQueue(v.loc,final,queueCount(v.loc,final)-n);v.manifest[final]=(v.manifest[final]||0)+n;v.pas+=n;free-=n}if(v.pas>0&&v.pas>=target(v))depart(v)}
function releaseBoarding(v){if(v.st!=='boarding')return false;let returned=0;for(const[final,n]of Object.entries(v.manifest||{})){if(n<=0)continue;setQueue(v.loc,final,queueCount(v.loc,final)+n);returned+=n}v.pas=0;v.manifest={};v.dst=null;v.pair=null;v.plannedDst='';v.st='idle';refreshRouteLine();toast(returned?`${v.name}: sefer iptal edildi · ${returned} yolcu limana döndü`:`${v.name}: otomatik tur kapatıldı · gemi serbest`);return true}
function depart(v){if(v.st!=='boarding'||!v.dst||!v.pas)return;v.lastRevenue=v.pas*fareFor(v.loc,v.dst);S.cash+=v.lastRevenue;v.currentOp=0;v.st='sailing';v.p=0;toast(`${ports[v.loc].name} çıkışı · ${v.pas} yolcu · ${money(v.lastRevenue)} gelir`)}
function arrive(v){const r=route(v.loc,v.dst);v.lastOp=v.currentOp;v.totalKm+=r.distanceKm;v.kmMaint+=r.distanceKm;if(v.kmMaint>=C.maintEvery){S.cash-=C.maintCost;v.kmMaint%=C.maintEvery;toast(`${v.name}: bakım yapıldı · ${money(C.maintCost)}`)}const arrived=v.dst;for(const[final,n]of Object.entries(v.manifest||{}))if(final!==arrived&&n>0)setQueue(arrived,final,queueCount(arrived,final)+n);v.loc=arrived;v.p=0;v.pas=0;v.manifest={};v.currentOp=0;if(v.autoTour&&v.pair){v.dst=v.pair[0]===v.loc?v.pair[1]:v.pair[0];v.st='boarding';board(v)}else{v.dst=null;v.pair=null;v.st='idle'}refreshRouteLine()}
function position(v){const pts=route(v.loc,v.dst).waypoints;if(v.p<=0)return pts[0];if(v.p>=1)return pts.at(-1);let lens=[],tot=0;for(let i=0;i<pts.length-1;i++){const l=L.latLng(pts[i]).distanceTo(pts[i+1]);lens.push(l);tot+=l}let t=tot*v.p;for(let i=0;i<lens.length;i++){if(t<=lens[i]){const z=t/lens[i];return[pts[i][0]+(pts[i+1][0]-pts[i][0])*z,pts[i][1]+(pts[i+1][1]-pts[i][1])*z]}t-=lens[i]}return pts.at(-1)}
function step(gm){if(!gm)return;S.m+=gm;generate(gm);for(const v of S.vehicles){if(v.st==='boarding'){S.cash-=gm*C.dockTax;board(v)}else if(v.st==='sailing'){const r=route(v.loc,v.dst),old=v.p,trip=r.durationMinutes*35/spec(v).speed;v.p=Math.min(1,v.p+gm/trip);const d=(v.p-old)*r.distanceKm,load=v.pas/spec(v).capacity,cost=d*spec(v).opKm*(1+C.loadCostMax*load);v.currentOp+=cost;S.cash-=cost;if(v.p>=1)arrive(v)}}const m=Math.floor(S.m);if(m!==lastSaveMinute&&m%5===0){save();lastSaveMinute=m}}
function refreshRouteLine(){const v=vehicle();routeLine.setLatLngs(v.dst?route(v.loc,v.dst).waypoints:[])}
function destinationOptions(){const v=vehicle(),o=['<option value="">Varış limanı seç</option>'];for(const id of S.unlocked){if(id===v.loc||!usableDirectRoute(v.loc,id))continue;const r=route(v.loc,id);if(r.distanceKm<=spec(v).range)o.push(`<option value="${id}">${ports[v.loc].name} → ${ports[id].name} · ${r.distanceKm.toFixed(0)} km · ${money(fareFor(v.loc,id))}</option>`)}E.destination.innerHTML=o.join('');E.destination.value=v.plannedDst||'';E.destination.disabled=v.st!=='idle';E.startTrip.disabled=v.st!=='idle'||!v.plannedDst}
function startManualTrip(){const v=vehicle(),d=v.plannedDst;if(v.st!=='idle'||!d||!usableDirectRoute(v.loc,d))return;v.dst=d;v.pair=v.autoTour?[v.loc,d]:null;v.st='boarding';v.pas=0;v.manifest={};v.plannedDst='';refreshRouteLine();board(v);render();save();toast(`${v.name}: ${ports[v.loc].name} → ${ports[d].name} seferi hazır`)}
function updatePortHover(){for(const id of PORT_IDS){const el=document.getElementById(`pv-${id}`);if(!el)continue;if(!unlocked(id)){const item=PORT_MARKET[id],affordable=item&&S.cash>=item.price;el.innerHTML=`<div>${money(item?.price||0)} · Marketspace &gt; Limanlar</div>${affordable?'<div class="pg v">Satın almak için limana tıkla</div>':''}`;continue}const rows=[],outgoing=S.unlocked.filter(next=>next!==id&&usableDirectRoute(id,next));for(const next of outgoing){const finals=S.unlocked.filter(final=>final!==id&&nextHop(id,final)===next),total=finals.reduce((sum,final)=>sum+queueCount(id,final),0),transfers=finals.filter(final=>final!==next&&queueCount(id,final)>0).map(final=>`${queueCount(id,final)} ${ports[final].name}`);rows.push(`<div><strong>${total}</strong> yolcu ${ports[next].name} yönü için bekliyor.</div>`);if(transfers.length)rows.push(`<div class="transfer-breakdown"><strong>Aktarma:</strong> ${transfers.join(', ')}</div>`)}const scores=S.unlocked.filter(x=>x!==id).map(x=>demandScore(id,x)).filter(Boolean);rows.push(`<div class="pp">Talep: ${level(scores.length?Math.max(...scores):0)}</div>`);for(const ship of S.vehicles)if(ship.loc===id&&ship.st!=='sailing')rows.push(`<div class="pg v">${ship.name} bu limanda</div>`);el.innerHTML=rows.join('')}}
function shipCards(){const spawn=S.unlocked.map(id=>`<option value="${id}">${ports[id].name}</option>`).join('');return Object.entries(TYPES).map(([id,t])=>`<div class="market-card"><h3>${t.symbol} ${t.name}</h3><div class="market-meta">Kapasite: ${t.capacity} · Hız: ${t.speed} km/sa · Menzil: ${t.range} km · Boş operasyon: €${t.opKm.toFixed(2)}/km</div><label class="market-spawn">Başlangıç limanı<select data-spawn="${id}">${spawn}</select></label><button data-buy="${id}" ${S.cash<t.price?'disabled':''}>${money(t.price)} · Satın al</button></div>`).join('')}
function portCards(){return PORT_IDS.map(id=>{const item=PORT_MARKET[id];if(!item)return'';const owned=unlocked(id);return`<div class="market-card"><h3>${ports[id].name}</h3><div class="market-meta">${item.country==='TR'?'Türkiye':'Yunanistan'} limanı · Hat lisansları ayrıca alınır.</div><button data-buy-port="${id}" ${owned||S.cash<item.price?'disabled':''}>${owned?'Liman açık':portPurchaseText(id)}</button></div>`}).join('')}
function lineCards(){return Object.entries(LINE_MARKET).map(([id,item])=>{const owned=S.openedLines.includes(id),ready=unlocked(item.origin)&&unlocked(item.destination),label=`${ports[item.origin].name} ↔ ${ports[item.destination].name}`,req=ready?(item.domestic?'Yurt içi hat lisansı':'Uluslararası hat lisansı'):`Önce ${ports[item.origin].name} ve ${ports[item.destination].name} limanlarını aç`;return`<div class="market-card"><h3>${label}</h3><div class="market-meta">${req}</div><button data-buy-line="${id}" ${owned||!ready||S.cash<item.price?'disabled':''}>${owned?'Hat lisansı açık':`${money(item.price)} · Lisansı al`}</button></div>`}).join('')}
function progressCards(){return Object.entries(SPEED_UPGRADES).map(([tier,u])=>{const owned=S.speedTiers.includes(Number(tier));return`<div class="market-card"><h3>${tier}× oyun hızı</h3><div class="market-meta">Simülasyonu ${tier} kat hızda çalıştırır. Temel zaman: 1 gerçek saniye = 1 oyun dakikası.</div><button data-buy-speed="${tier}" ${owned||S.cash<u.cost?'disabled':''}>${owned?'Satın alındı':`${money(u.cost)} · Aç`}</button></div>`}).join('')}
function renderMarket(){document.querySelectorAll('.market-tab').forEach(b=>b.classList.toggle('active',b.dataset.marketTab===S.marketTab));E.marketCards.innerHTML=S.marketTab==='vehicles'?shipCards():S.marketTab==='ports'?portCards():S.marketTab==='lines'?lineCards():progressCards();document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buyShip(b.dataset.buy,document.querySelector(`[data-spawn="${b.dataset.buy}"]`)?.value));document.querySelectorAll('[data-buy-port]').forEach(b=>b.onclick=()=>buyPort(b.dataset.buyPort));document.querySelectorAll('[data-buy-line]').forEach(b=>b.onclick=()=>buyLine(b.dataset.buyLine));document.querySelectorAll('[data-buy-speed]').forEach(b=>b.onclick=()=>buySpeed(Number(b.dataset.buySpeed)))}
function buyShip(typeId,spawn){const t=TYPES[typeId];if(!t||!spawn||!unlocked(spawn)||S.cash<t.price)return;S.cash-=t.price;const n=S.vehicles.length+1,id=`v${n}`;S.vehicles.push(newVehicle(id,typeId,typeId==='swift80'?`MV Hızır ${n}`:`MV Ege ${n}`,spawn,n-1));S.selected=id;rebuildShips();showView('fleet');render();save();toast(`${S.vehicles.at(-1).name}, ${ports[spawn].name} limanında filoya katıldı.`)}
function buyPort(id){const item=PORT_MARKET[id];if(!item||unlocked(id)||S.cash<item.price)return;S.cash-=item.price;S.unlocked.push(id);rebuildPortIcons();renderMarket();render();save();toast(`${ports[id].name} limanı açıldı.`)}
function buyLine(id){const item=LINE_MARKET[id];if(!item||S.openedLines.includes(id)||!unlocked(item.origin)||!unlocked(item.destination)||S.cash<item.price)return;S.cash-=item.price;S.openedLines.push(id);renderMarket();render();save();toast(`${ports[item.origin].name} ↔ ${ports[item.destination].name} hat lisansı alındı.`)}
function buySpeed(tier){const u=SPEED_UPGRADES[tier];if(!u||S.speedTiers.includes(tier)||S.cash<u.cost)return;S.cash-=u.cost;S.speedTiers.push(tier);renderMarket();render();save();toast(`${tier}× oyun hızı açıldı.`)}function showView(view){E.fleetPanel.hidden=view!=='fleet';E.marketPanel.hidden=view!=='market';document.querySelectorAll('.navtab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='market')renderMarket()}
function render(){const v=vehicle(),t=spec(v),d=now(),[sn]=seasonBand(d),[tn]=timeBand(d),pct=Math.round(v.pas/t.capacity*100);E.date.textContent=`${new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long',year:'numeric'}).format(d)} · ${new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(d)}`;E.season.textContent=sn;E.time.textContent=tn;E.cash.textContent=money(S.cash);E.vehicleSelect.innerHTML=S.vehicles.map(x=>`<option value="${x.id}" ${x.id===v.id?'selected':''}>${spec(x).symbol} ${x.name}</option>`).join('');E.status.textContent=v.st==='idle'?`${ports[v.loc].name}'ta bekliyor · yolcu almıyor`:v.st==='boarding'?`${ports[v.loc].name}'ta yolcu alıyor · vergi işliyor`:`${ports[v.dst].name}'e seyrediyor`;E.routeBadge.textContent=v.pair?`${ports[v.pair[0]].name} ↔ ${ports[v.pair[1]].name}`:v.dst?`${ports[v.loc].name} → ${ports[v.dst].name}`:'Sefer yok';E.onb.textContent=v.pas;E.capacity.textContent=t.capacity;E.lastRevenue.textContent=money(v.lastRevenue);E.operation.textContent=money(v.st==='sailing'?v.currentOp:v.lastOp);E.maint.textContent=`${Math.floor(v.kmMaint)}/${C.maintEvery}`;E.fareText.textContent=v.dst?money(fareFor(v.loc,v.dst,d)):v.plannedDst?money(fareFor(v.loc,v.plannedDst,d)):'Hat seçilmedi';E.fullness.value=v.fullness;E.fullnessText.textContent=`%${v.fullness}`;E.autoTour.checked=v.autoTour;E.rangeBadge.textContent=`Menzil ${t.range} km`;E.goal.textContent=v.fullness===0?'Hedef: ilk yolcu':`Hedef: ${target(v)} yolcu`;E.progressLabel.textContent=`Kalkış hedefi: %${pct}`;E.fill.style.width=`${Math.min(100,pct)}%`;for(const ship of S.vehicles)shipMarkers[ship.id].setLatLng(ship.st==='sailing'?position(ship):ports[ship.loc].terminal);destinationOptions();updatePortHover();document.querySelectorAll('[data-s]').forEach(b=>{const tier=Number(b.dataset.speedTier||0),allowed=!tier||S.speedTiers.includes(tier);b.disabled=!allowed;b.title=allowed?'':`${tier}× hız Marketspace > İlerlemeler bölümünden açılır`;b.classList.toggle('a',Number(b.dataset.s)===S.s)})}
E.destination.onchange=()=>{vehicle().plannedDst=E.destination.value;render();save()};E.startTrip.onclick=startManualTrip;E.vehicleSelect.onchange=()=>{S.selected=E.vehicleSelect.value;refreshRouteLine();render();save()};E.autoTour.onchange=()=>{const v=vehicle();v.autoTour=E.autoTour.checked;if(!v.autoTour){v.pair=null;if(v.st==='boarding')releaseBoarding(v)}else if(v.st==='boarding'&&v.dst)v.pair=[v.loc,v.dst];render();save()};E.fullness.oninput=()=>{const v=vehicle();v.fullness=Number(E.fullness.value);if(v.st==='boarding')board(v);render();save()};document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{if(b.disabled)return;S.s=Number(b.dataset.s);render();save()});document.querySelectorAll('.navtab').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('.market-tab').forEach(b=>b.onclick=()=>{S.marketTab=b.dataset.marketTab;renderMarket();save()});E.reset.onclick=()=>{localStorage.removeItem(C.key);localStorage.removeItem(C.old);S=fresh();rebuildShips();refreshRouteLine();rebuildPortIcons();showView('fleet');render();save();toast('Oyun sıfırlandı.')};
function save(){localStorage.setItem(C.key,JSON.stringify(S))}function migrateVehicle(v,index){const loc=['ayvalik','kucukkuyu'].includes(v.loc)?v.loc:'ayvalik';const x={...newVehicle(v.id,v.type,v.name,loc,v.colorIndex??index),...v,loc,manifest:v.manifest||{}};delete x.price;return x}function load(){try{const raw=localStorage.getItem(C.key)||localStorage.getItem(C.old);if(!raw)return;const p=JSON.parse(raw),legacy=Number(p.v||0)<9;S={...fresh(),...p};S.vehicles=(p.vehicles||fresh().vehicles).map(migrateVehicle);const base=emptyQueues();for(const a of PORT_IDS)for(const b of PORT_IDS)if(a!==b)base[a][b]=p.w?.[a]?.[b]??base[a][b];S.w=base;if(legacy){S.unlocked=['ayvalik','kucukkuyu'];S.openedLines=['ayvalik-kucukkuyu']}else{S.unlocked=(p.unlocked||['ayvalik','kucukkuyu']).filter(id=>PORT_IDS.includes(id));S.openedLines=(p.openedLines||['ayvalik-kucukkuyu']).filter(id=>LINE_MARKET[id])}S.speedTiers=p.speedTiers||[1,2];if(![0,1,2,4,8].includes(S.s))S.s=1;S.marketTab=['vehicles','ports','lines','progress'].includes(p.marketTab)?p.marketTab:'vehicles';S.v=9}catch{S=fresh()}}
load();rebuildShips();refreshRouteLine();rebuildPortIcons();showView('fleet');render();function loop(ts){const realSeconds=Math.min(.25,(ts-lastFrame)/1000);lastFrame=ts;if(S.s>0)step(realSeconds*S.s);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
