import { RouteEngine } from './route-engine.js';

const engine = await RouteEngine.load();
const PORT_IDS = Object.values(engine.nodes).filter(node => node.type === 'port').map(node => node.id);
const TYPES = {
  coastal60: { name: 'Coastal Ferry 60', capacity: 60, speed: 35, range: 180, opKm: 6.5, price: 35000, symbol: '⛴' },
  swift80: { name: 'HSC Aegean Swift 80', capacity: 80, speed: 55, range: 260, opKm: 9.5, price: 85000, symbol: '➤' }
};
const COLORS = ['#173f5f', '#c96c4a', '#19795d', '#7a5fa3', '#b8860b', '#2f6f8f', '#8c4b62', '#4f6b3a'];
const PORT_MARKET = {
  ayvalik: { price: 0, country: 'TR' },
  kucukkuyu: { price: 0, country: 'TR' },
  cesme: { price: 20000, country: 'TR' },
  chios: { price: 25000, country: 'GR' },
  mytilene: { price: 30000, country: 'GR' }
};
const C = { base: 0.72, key: 'aegean-fleet-fleet-v10', old: 'aegean-fleet-fleet-v9', start: new Date(2020, 4, 1, 8), dockTax: 0.08, maintEvery: 500, maintCost: 180, startCash: 2000, loadCostMax: 0.18 };
const SUMMER_FARES = { 'ayvalik-kucukkuyu': 16, 'ayvalik-mytilene': 25, 'ayvalik-cesme': 32, 'cesme-chios': 22, 'chios-mytilene': 34 };
const FARE_MULT = { summer: 1, shoulder: 0.92, low: 0.81, winter: 0.72 };
const SPEED_UPGRADES = { 4: { cost: 30000 }, 8: { cost: 120000 } };
const ports = Object.fromEntries(PORT_IDS.map(id => [id, engine.getNode(id)]));
const q = id => document.getElementById(id);
const route = (a, b) => engine.getRoute({ mode: 'sea', origin: a, destination: b });
const routeKey = (a, b) => [a, b].sort().join('-');
const routeDefined = (a, b) => Boolean(engine.routeData?.routes?.[`${a}-${b}`] || engine.routeData?.routes?.[`${b}-${a}`]);
function seasonBand(date) { const month = date.getMonth() + 1; if ([6, 7, 8].includes(month)) return ['Yaz sezonu', 'summer', 1.55]; if ([5, 9].includes(month)) return ['Ara sezon', 'shoulder', 1.15]; if ([4, 10].includes(month)) return ['Sakin sezon', 'low', 0.58]; return ['Kış sezonu', 'winter', 0.22]; }
function timeBand(date) { const hour = date.getHours() + date.getMinutes() / 60; if (hour >= 7 && hour < 10) return ['Sabah yoğunluğu', 1.45]; if (hour >= 16 && hour < 20) return ['Akşam yoğunluğu', 1.65]; if (hour >= 23 || hour < 7) return ['Gece talebi', 0.18]; return ['Gündüz talebi', 1]; }
function distanceDemandFactor(km) { if (km <= 20) return 1.1; if (km <= 50) return 1.04; if (km <= 100) return 0.98; return 0.92; }
function fareFor(a, b, date = now()) { const base = SUMMER_FARES[routeKey(a, b)] ?? Math.round(18 + route(a, b).distanceKm * 0.13); return Math.round(base * FARE_MULT[seasonBand(date)[1]]); }
function newVehicle(id, type = 'coastal60', name = 'MV Ege', loc = 'ayvalik', colorIndex = 0) { return { id, type, name, loc, colorIndex, dst: null, pair: null, st: 'idle', pas: 0, manifest: {}, p: 0, fullness: 80, autoTour: false, plannedDst: '', lastRevenue: 0, lastOp: 0, currentOp: 0, kmMaint: 0, totalKm: 0 }; }
function emptyQueues() { const queues = {}; for (const origin of PORT_IDS) { queues[origin] = {}; for (const destination of PORT_IDS) if (origin !== destination) queues[origin][destination] = 0; } queues.ayvalik.kucukkuyu = 4; queues.kucukkuyu.ayvalik = 3; return queues; }
function fresh() { return { m: 0, s: 1, cash: C.startCash, unlocked: ['ayvalik', 'kucukkuyu'], openedLines: [], speedTiers: [1, 2], vehicles: [newVehicle('v1')], selected: 'v1', w: emptyQueues(), fr: {}, v: 10, marketTab: 'vehicles' }; }
let S = fresh(), markers = {}, shipMarkers = {}, routeLine = L.polyline([], { color: '#315f78', weight: 3, opacity: 0.75, dashArray: '8 10' }), lastFrame = performance.now(), lastSaveMinute = -1, toastTimer;
const E = { date: q('date'), season: q('season'), time: q('time'), cash: q('cash'), fleetPanel: q('fleetPanel'), marketPanel: q('marketPanel'), vehicleSelect: q('vehicleSelect'), status: q('status'), routeBadge: q('routeBadge'), onb: q('onb'), capacity: q('capacity'), lastRevenue: q('lastRevenue'), operation: q('operation'), maint: q('maint'), destination: q('destination'), startTrip: q('startTrip'), fareText: q('fareText'), fullness: q('fullness'), fullnessText: q('fullnessText'), autoTour: q('autoTour'), progressLabel: q('progressLabel'), goal: q('goal'), fill: q('fill'), marketCards: q('marketCards'), toast: q('toast'), reset: q('reset'), rangeBadge: q('rangeBadge') };
const map = L.map('map', { center: [39.32, 26.5], zoom: 9, minZoom: 7, maxZoom: 13, zoomControl: false, attributionControl: false });
L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}{r}.png', { maxZoom: 13 }).addTo(map); L.control.zoom({ position: 'bottomleft' }).addTo(map); routeLine.addTo(map);
const vehicle = () => S.vehicles.find(v => v.id === S.selected) || S.vehicles[0], spec = v => TYPES[v.type], unlocked = id => S.unlocked.includes(id), usableDirectRoute = (a, b) => unlocked(a) && unlocked(b) && routeDefined(a, b);
function money(value) { return new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value); }
function toast(message) { E.toast.textContent = message; E.toast.classList.add('s'); clearTimeout(toastTimer); toastTimer = setTimeout(() => E.toast.classList.remove('s'), 3000); }
function now() { return new Date(C.start.getTime() + S.m * 60000); }
function findTransferPath(origin, destination) { if (origin === destination) return [origin]; if (usableDirectRoute(origin, destination)) return [origin, destination]; const available = S.unlocked.filter(id => PORT_IDS.includes(id)), paths = [[origin]], visited = new Set([origin]); while (paths.length) { const path = paths.shift(), current = path.at(-1); for (const next of available) { if (next === current || visited.has(next) || !usableDirectRoute(current, next)) continue; const nextPath = [...path, next]; if (next === destination) return nextPath; visited.add(next); paths.push(nextPath); } } return null; }
const nextHop = (a, b) => findTransferPath(a, b)?.[1] || null;
function demandScore(a, b, date = now()) { const path = findTransferPath(a, b); if (!path) return 0; return seasonBand(date)[2] * timeBand(date)[1] * (ports[a].intensity || 0.6) * distanceDemandFactor(route(path[0], path[1]).distanceKm); }
function level(value) { return value >= 1.25 ? 'Çok yoğun' : value >= 0.85 ? 'Yoğun' : value >= 0.5 ? 'Normal' : value >= 0.25 ? 'Sakin' : 'Çok sakin'; }
function queueCount(a, b) { return S.w[a]?.[b] ?? 0; } function setQueue(a, b, count) { (S.w[a] ??= {})[b] = Math.max(0, Math.round(count)); } function frac(a, b) { return S.fr[`${a}:${b}`] || 0; } function setFrac(a, b, value) { S.fr[`${a}:${b}`] = value; } function target(v) { return Math.ceil(spec(v).capacity * v.fullness / 100); }
function portPurchaseText(id) { const item = PORT_MARKET[id]; if (!item || item.price === 0) return 'Başlangıç limanı'; return `${money(item.price)} · Limanı aç`; }
function portIcon(id, index) { const locked = !unlocked(id), side = index % 2 ? 'l' : 'r'; return L.divIcon({ className: '', html: `<div class="ps ${side} ${locked ? 'locked' : ''}"><div class="pd"></div><div class="pc"><div class="pt">${ports[id].name}${locked ? ' · Kilitli' : ''}</div><div class="pv" id="pv-${id}"></div></div></div>`, iconSize: [18, 18], iconAnchor: [9, 9] }); }
function openPortPopup(id) { if (unlocked(id)) return; const item = PORT_MARKET[id]; if (!item) return; const canBuy = S.cash >= item.price, html = `<div class="port-buy-popup"><strong>${ports[id].name}</strong><div>${money(item.price)}</div><div style="margin-top:5px;font-size:11px">Liman açılınca mevcut bağlantıları otomatik kullanıma girer.</div><button id="buy-port-popup" ${canBuy ? '' : 'disabled'}>${canBuy ? 'Limanı satın al' : 'Yetersiz bakiye'}</button></div>`, popup = L.popup({ closeButton: true, offset: [0, -8] }).setLatLng(ports[id].terminal).setContent(html).openOn(map); setTimeout(() => { const button = document.getElementById('buy-port-popup'); if (button && !button.disabled) button.onclick = () => { buyPort(id); map.closePopup(popup); }; }, 0); }
PORT_IDS.forEach((id, index) => { const marker = L.marker(ports[id].terminal, { icon: portIcon(id, index), zIndexOffset: 400 }).addTo(map); marker.on('click', () => openPortPopup(id)); markers[id] = marker; });
function shipIcon(v) { const type = spec(v), color = COLORS[v.colorIndex % COLORS.length]; return L.divIcon({ className: '', html: `<div class="sc ship-${v.type}" style="--ship-color:${color}">${type.symbol}</div>`, iconSize: [32, 32], iconAnchor: [16, 16] }); }
function addVehicleMarker(v) { const marker = L.marker(ports[v.loc].terminal, { icon: shipIcon(v), zIndexOffset: 1000 }).addTo(map).bindTooltip(v.name, { permanent: true, direction: 'top', offset: [0, -16], className: 'sl' }); marker.on('click', () => { S.selected = v.id; showView('fleet'); render(); }); shipMarkers[v.id] = marker; }
function rebuildShips() { Object.values(shipMarkers).forEach(marker => marker.remove()); shipMarkers = {}; S.vehicles.forEach(addVehicleMarker); } function rebuildPortIcons() { PORT_IDS.forEach((id, index) => markers[id].setIcon(portIcon(id, index))); }
function generate(minutes) { const date = now(); for (const origin of S.unlocked) for (const destination of S.unlocked) { if (origin === destination || !findTransferPath(origin, destination)) continue; const total = frac(origin, destination) + minutes * C.base * demandScore(origin, destination, date), created = Math.floor(total); if (created) setQueue(origin, destination, queueCount(origin, destination) + created); setFrac(origin, destination, total - created); } }
function board(v) { if (v.st !== 'boarding' || !v.dst) return; let free = spec(v).capacity - v.pas; const candidates = S.unlocked.filter(final => final !== v.loc && queueCount(v.loc, final) > 0 && nextHop(v.loc, final) === v.dst).sort((a, b) => Number(a !== v.dst) - Number(b !== v.dst)); for (const final of candidates) { if (free <= 0) break; const count = Math.min(free, queueCount(v.loc, final)); setQueue(v.loc, final, queueCount(v.loc, final) - count); v.manifest[final] = (v.manifest[final] || 0) + count; v.pas += count; free -= count; } if (v.pas > 0 && v.pas >= target(v)) depart(v); }
function releaseBoarding(v) { if (v.st !== 'boarding') return false; let returned = 0; for (const [final, count] of Object.entries(v.manifest || {})) { if (count <= 0) continue; setQueue(v.loc, final, queueCount(v.loc, final) + count); returned += count; } v.pas = 0; v.manifest = {}; v.dst = null; v.pair = null; v.plannedDst = ''; v.st = 'idle'; refreshRouteLine(); toast(returned ? `${v.name}: sefer iptal edildi · ${returned} yolcu limana döndü` : `${v.name}: otomatik tur kapatıldı · gemi serbest`); return true; }
function depart(v) { if (v.st !== 'boarding' || !v.dst || !v.pas) return; v.lastRevenue = v.pas * fareFor(v.loc, v.dst); S.cash += v.lastRevenue; v.currentOp = 0; v.st = 'sailing'; v.p = 0; toast(`${ports[v.loc].name} çıkışı · ${v.pas} yolcu · ${money(v.lastRevenue)} gelir`); }
function arrive(v) { const currentRoute = route(v.loc, v.dst); v.lastOp = v.currentOp; v.totalKm += currentRoute.distanceKm; v.kmMaint += currentRoute.distanceKm; if (v.kmMaint >= C.maintEvery) { S.cash -= C.maintCost; v.kmMaint %= C.maintEvery; toast(`${v.name}: bakım yapıldı · ${money(C.maintCost)}`); } const arrived = v.dst; for (const [final, count] of Object.entries(v.manifest || {})) if (final !== arrived && count > 0) setQueue(arrived, final, queueCount(arrived, final) + count); v.loc = arrived; v.p = 0; v.pas = 0; v.manifest = {}; v.currentOp = 0; if (v.autoTour && v.pair) { v.dst = v.pair[0] === v.loc ? v.pair[1] : v.pair[0]; v.st = 'boarding'; board(v); } else { v.dst = null; v.pair = null; v.st = 'idle'; } refreshRouteLine(); }
function position(v) { const points = route(v.loc, v.dst).waypoints; if (v.p <= 0) return points[0]; if (v.p >= 1) return points.at(-1); const lengths = []; let total = 0; for (let i = 0; i < points.length - 1; i++) { const length = L.latLng(points[i]).distanceTo(points[i + 1]); lengths.push(length); total += length; } let targetDistance = total * v.p; for (let i = 0; i < lengths.length; i++) { if (targetDistance <= lengths[i]) { const ratio = targetDistance / lengths[i]; return [points[i][0] + (points[i + 1][0] - points[i][0]) * ratio, points[i][1] + (points[i + 1][1] - points[i][1]) * ratio]; } targetDistance -= lengths[i]; } return points.at(-1); }
function step(gameMinutes) { if (!gameMinutes) return; S.m += gameMinutes; generate(gameMinutes); for (const v of S.vehicles) { if (v.st === 'boarding') { S.cash -= gameMinutes * C.dockTax; board(v); } else if (v.st === 'sailing') { const currentRoute = route(v.loc, v.dst), oldProgress = v.p, tripMinutes = currentRoute.durationMinutes * 35 / spec(v).speed; v.p = Math.min(1, v.p + gameMinutes / tripMinutes); const distance = (v.p - oldProgress) * currentRoute.distanceKm, loadRatio = v.pas / spec(v).capacity, cost = distance * spec(v).opKm * (1 + C.loadCostMax * loadRatio); v.currentOp += cost; S.cash -= cost; if (v.p >= 1) arrive(v); } } const minute = Math.floor(S.m); if (minute !== lastSaveMinute && minute % 5 === 0) { save(); lastSaveMinute = minute; } }
function refreshRouteLine() { const v = vehicle(); routeLine.setLatLngs(v.dst ? route(v.loc, v.dst).waypoints : []); }
function destinationOptions() { const v = vehicle(), options = ['<option value="">Varış limanı seç</option>']; for (const id of S.unlocked) { if (id === v.loc || !usableDirectRoute(v.loc, id)) continue; const directRoute = route(v.loc, id); if (directRoute.distanceKm <= spec(v).range) options.push(`<option value="${id}">${ports[v.loc].name} → ${ports[id].name} · ${directRoute.distanceKm.toFixed(0)} km · ${money(fareFor(v.loc, id))}</option>`); } E.destination.innerHTML = options.join(''); E.destination.value = v.plannedDst || ''; E.destination.disabled = v.st !== 'idle'; E.startTrip.disabled = v.st !== 'idle' || !v.plannedDst; }
function startManualTrip() { const v = vehicle(), destination = v.plannedDst; if (v.st !== 'idle' || !destination || !usableDirectRoute(v.loc, destination)) return; v.dst = destination; v.pair = v.autoTour ? [v.loc, destination] : null; v.st = 'boarding'; v.pas = 0; v.manifest = {}; v.plannedDst = ''; refreshRouteLine(); board(v); render(); save(); toast(`${v.name}: ${ports[v.loc].name} → ${ports[destination].name} seferi hazır`); }
function updatePortHover() { for (const id of PORT_IDS) { const element = document.getElementById(`pv-${id}`); if (!element) continue; if (!unlocked(id)) { const item = PORT_MARKET[id], affordable = item && S.cash >= item.price; element.innerHTML = `<div>${money(item?.price || 0)} · Marketspace &gt; Limanlar</div><div class="transfer-breakdown">Açılınca bağlantılar ücretsiz etkinleşir.</div>${affordable ? '<div class="pg v">Satın almak için limana tıkla</div>' : ''}`; continue; } const rows = [], outgoing = S.unlocked.filter(next => next !== id && usableDirectRoute(id, next)); for (const next of outgoing) { const finals = S.unlocked.filter(final => final !== id && nextHop(id, final) === next), total = finals.reduce((sum, final) => sum + queueCount(id, final), 0), transfers = finals.filter(final => final !== next && queueCount(id, final) > 0).map(final => `${queueCount(id, final)} ${ports[final].name}`); rows.push(`<div><strong>${total}</strong> yolcu ${ports[next].name} yönü için bekliyor.</div>`); if (transfers.length) rows.push(`<div class="transfer-breakdown"><strong>Aktarma:</strong> ${transfers.join(', ')}</div>`); } const scores = S.unlocked.filter(destination => destination !== id).map(destination => demandScore(id, destination)).filter(Boolean); rows.push(`<div class="pp">Talep: ${level(scores.length ? Math.max(...scores) : 0)}</div>`); for (const ship of S.vehicles) if (ship.loc === id && ship.st !== 'sailing') rows.push(`<div class="pg v">${ship.name} bu limanda</div>`); element.innerHTML = rows.join(''); } }
function shipCards() { const spawn = S.unlocked.map(id => `<option value="${id}">${ports[id].name}</option>`).join(''); return Object.entries(TYPES).map(([id, type]) => `<div class="market-card"><h3>${type.symbol} ${type.name}</h3><div class="market-meta">Kapasite: ${type.capacity} · Hız: ${type.speed} km/sa · Menzil: ${type.range} km · Boş operasyon: €${type.opKm.toFixed(2)}/km</div><label class="market-spawn">Başlangıç limanı<select data-spawn="${id}">${spawn}</select></label><button data-buy="${id}" ${S.cash < type.price ? 'disabled' : ''}>${money(type.price)} · Satın al</button></div>`).join(''); }
function portCards() { return PORT_IDS.map(id => { const item = PORT_MARKET[id]; if (!item) return ''; const owned = unlocked(id), links = PORT_IDS.filter(other => other !== id && routeDefined(id, other)).map(other => ports[other].name).join(', '); return `<div class="market-card"><h3>${ports[id].name}</h3><div class="market-meta">${item.country === 'TR' ? 'Türkiye' : 'Yunanistan'} limanı · Açıldığında sahip olduğun limanlarla mevcut bağlantıları ücretsiz etkinleşir.<br>Bağlantılar: ${links || 'Henüz tanımlı değil'}</div><button data-buy-port="${id}" ${owned || S.cash < item.price ? 'disabled' : ''}>${owned ? 'Liman açık' : portPurchaseText(id)}</button></div>`; }).join(''); }
function shipsOnLine(a, b) { return S.vehicles.filter(v => (v.pair && routeKey(v.pair[0], v.pair[1]) === routeKey(a, b)) || (v.dst && routeKey(v.loc, v.dst) === routeKey(a, b))).length; }
function lineCards() { return Object.values(engine.routeData?.routes || {}).map(item => { const ready = unlocked(item.origin) && unlocked(item.destination), label = `${ports[item.origin].name} ↔ ${ports[item.destination].name}`, demand = ready ? level(Math.max(demandScore(item.origin, item.destination), demandScore(item.destination, item.origin))) : 'Limanlar kapalı', ships = shipsOnLine(item.origin, item.destination); return `<div class="market-card"><h3>${label}</h3><div class="market-meta">${item.distanceKm.toFixed(1)} km · ${item.durationMinutes} dk · Yaz tarifesi ${money(fareFor(item.origin, item.destination, new Date(2020, 6, 1, 12)))}<br>Talep: ${demand} · Çalışan gemi: ${ships}</div><button disabled>${ready ? 'Hat kullanıma açık' : 'İki limanı da açınca etkinleşir'}</button></div>`; }).join(''); }
function progressCards() { return Object.entries(SPEED_UPGRADES).map(([tier, upgrade]) => { const owned = S.speedTiers.includes(Number(tier)); return `<div class="market-card"><h3>${tier}× oyun hızı</h3><div class="market-meta">Simülasyonu ${tier} kat hızda çalıştırır. Temel zaman: 1 gerçek saniye = 1 oyun dakikası.</div><button data-buy-speed="${tier}" ${owned || S.cash < upgrade.cost ? 'disabled' : ''}>${owned ? 'Satın alındı' : `${money(upgrade.cost)} · Aç`}</button></div>`; }).join(''); }
function renderMarket() { document.querySelectorAll('.market-tab').forEach(button => button.classList.toggle('active', button.dataset.marketTab === S.marketTab)); E.marketCards.innerHTML = S.marketTab === 'vehicles' ? shipCards() : S.marketTab === 'ports' ? portCards() : S.marketTab === 'lines' ? lineCards() : progressCards(); document.querySelectorAll('[data-buy]').forEach(button => button.onclick = () => buyShip(button.dataset.buy, document.querySelector(`[data-spawn="${button.dataset.buy}"]`)?.value)); document.querySelectorAll('[data-buy-port]').forEach(button => button.onclick = () => buyPort(button.dataset.buyPort)); document.querySelectorAll('[data-buy-speed]').forEach(button => button.onclick = () => buySpeed(Number(button.dataset.buySpeed))); }
function buyShip(typeId, spawn) { const type = TYPES[typeId]; if (!type || !spawn || !unlocked(spawn) || S.cash < type.price) return; S.cash -= type.price; const number = S.vehicles.length + 1, id = `v${number}`; S.vehicles.push(newVehicle(id, typeId, typeId === 'swift80' ? `MV Hızır ${number}` : `MV Ege ${number}`, spawn, number - 1)); S.selected = id; rebuildShips(); showView('fleet'); render(); save(); toast(`${S.vehicles.at(-1).name}, ${ports[spawn].name} limanında filoya katıldı.`); }
function buyPort(id) { const item = PORT_MARKET[id]; if (!item || unlocked(id) || S.cash < item.price) return; S.cash -= item.price; S.unlocked.push(id); const activated = S.unlocked.filter(other => other !== id && routeDefined(id, other)).length; rebuildPortIcons(); renderMarket(); render(); save(); toast(`${ports[id].name} limanı açıldı · ${activated} bağlantı etkinleşti.`); }
function buySpeed(tier) { const upgrade = SPEED_UPGRADES[tier]; if (!upgrade || S.speedTiers.includes(tier) || S.cash < upgrade.cost) return; S.cash -= upgrade.cost; S.speedTiers.push(tier); renderMarket(); render(); save(); toast(`${tier}× oyun hızı açıldı.`); }
function showView(view) { E.fleetPanel.hidden = view !== 'fleet'; E.marketPanel.hidden = view !== 'market'; document.querySelectorAll('.navtab').forEach(button => button.classList.toggle('active', button.dataset.view === view)); if (view === 'market') renderMarket(); }
function render() { const v = vehicle(), type = spec(v), date = now(), [seasonName] = seasonBand(date), [timeName] = timeBand(date), percentage = Math.round(v.pas / type.capacity * 100); E.date.textContent = `${new Intl.DateTimeFormat('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' }).format(date)} · ${new Intl.DateTimeFormat('tr-TR', { hour: '2-digit', minute: '2-digit' }).format(date)}`; E.season.textContent = seasonName; E.time.textContent = timeName; E.cash.textContent = money(S.cash); E.vehicleSelect.innerHTML = S.vehicles.map(item => `<option value="${item.id}" ${item.id === v.id ? 'selected' : ''}>${spec(item).symbol} ${item.name}</option>`).join(''); E.status.textContent = v.st === 'idle' ? `${ports[v.loc].name}'ta bekliyor · yolcu almıyor` : v.st === 'boarding' ? `${ports[v.loc].name}'ta yolcu alıyor · vergi işliyor` : `${ports[v.dst].name}'e seyrediyor`; E.routeBadge.textContent = v.pair ? `${ports[v.pair[0]].name} ↔ ${ports[v.pair[1]].name}` : v.dst ? `${ports[v.loc].name} → ${ports[v.dst].name}` : 'Sefer yok'; E.onb.textContent = v.pas; E.capacity.textContent = type.capacity; E.lastRevenue.textContent = money(v.lastRevenue); E.operation.textContent = money(v.st === 'sailing' ? v.currentOp : v.lastOp); E.maint.textContent = `${Math.floor(v.kmMaint)}/${C.maintEvery}`; E.fareText.textContent = v.dst ? money(fareFor(v.loc, v.dst, date)) : v.plannedDst ? money(fareFor(v.loc, v.plannedDst, date)) : 'Hat seçilmedi'; E.fullness.value = v.fullness; E.fullnessText.textContent = `%${v.fullness}`; E.autoTour.checked = v.autoTour; E.rangeBadge.textContent = `Menzil ${type.range} km`; E.goal.textContent = v.fullness === 0 ? 'Hedef: ilk yolcu' : `Hedef: ${target(v)} yolcu`; E.progressLabel.textContent = `Kalkış hedefi: %${percentage}`; E.fill.style.width = `${Math.min(100, percentage)}%`; for (const ship of S.vehicles) shipMarkers[ship.id].setLatLng(ship.st === 'sailing' ? position(ship) : ports[ship.loc].terminal); destinationOptions(); updatePortHover(); document.querySelectorAll('[data-s]').forEach(button => { const tier = Number(button.dataset.speedTier || 0), allowed = !tier || S.speedTiers.includes(tier); button.disabled = !allowed; button.title = allowed ? '' : `${tier}× hız Marketspace > İlerlemeler bölümünden açılır`; button.classList.toggle('a', Number(button.dataset.s) === S.s); }); }
E.destination.onchange = () => { vehicle().plannedDst = E.destination.value; render(); save(); }; E.startTrip.onclick = startManualTrip; E.vehicleSelect.onchange = () => { S.selected = E.vehicleSelect.value; refreshRouteLine(); render(); save(); }; E.autoTour.onchange = () => { const v = vehicle(); v.autoTour = E.autoTour.checked; if (!v.autoTour) { v.pair = null; if (v.st === 'boarding') releaseBoarding(v); } else if (v.st === 'boarding' && v.dst) v.pair = [v.loc, v.dst]; render(); save(); }; E.fullness.oninput = () => { const v = vehicle(); v.fullness = Number(E.fullness.value); if (v.st === 'boarding') board(v); render(); save(); }; document.querySelectorAll('[data-s]').forEach(button => button.onclick = () => { if (button.disabled) return; S.s = Number(button.dataset.s); render(); save(); }); document.querySelectorAll('.navtab').forEach(button => button.onclick = () => showView(button.dataset.view)); document.querySelectorAll('.market-tab').forEach(button => button.onclick = () => { S.marketTab = button.dataset.marketTab; renderMarket(); save(); }); E.reset.onclick = () => { localStorage.removeItem(C.key); localStorage.removeItem(C.old); S = fresh(); rebuildShips(); refreshRouteLine(); rebuildPortIcons(); showView('fleet'); render(); save(); toast('Oyun sıfırlandı.'); };
function save() { localStorage.setItem(C.key, JSON.stringify(S)); }
function migrateVehicle(v, index) { const location = S.unlocked?.includes(v.loc) && PORT_IDS.includes(v.loc) ? v.loc : 'ayvalik'; const migrated = { ...newVehicle(v.id, v.type, v.name, location, v.colorIndex ?? index), ...v, loc: location, manifest: v.manifest || {} }; delete migrated.price; return migrated; }
function load() { try { const raw = localStorage.getItem(C.key) || localStorage.getItem(C.old); if (!raw) return; const parsed = JSON.parse(raw); S = { ...fresh(), ...parsed }; S.unlocked = (parsed.unlocked || ['ayvalik', 'kucukkuyu']).filter(id => PORT_IDS.includes(id)); if (!S.unlocked.includes('ayvalik')) S.unlocked.unshift('ayvalik'); if (!S.unlocked.includes('kucukkuyu')) S.unlocked.push('kucukkuyu'); S.vehicles = (parsed.vehicles || fresh().vehicles).map(migrateVehicle); const base = emptyQueues(); for (const a of PORT_IDS) for (const b of PORT_IDS) if (a !== b) base[a][b] = parsed.w?.[a]?.[b] ?? base[a][b]; S.w = base; S.openedLines = []; S.speedTiers = parsed.speedTiers || [1, 2]; if (![0, 1, 2, 4, 8].includes(S.s)) S.s = 1; S.marketTab = ['vehicles', 'ports', 'lines', 'progress'].includes(parsed.marketTab) ? parsed.marketTab : 'vehicles'; S.v = 10; } catch { S = fresh(); } }
load(); rebuildShips(); refreshRouteLine(); rebuildPortIcons(); showView('fleet'); render(); function loop(timestamp) { const realSeconds = Math.min(0.25, (timestamp - lastFrame) / 1000); lastFrame = timestamp; if (S.s > 0) step(realSeconds * S.s); render(); requestAnimationFrame(loop); } requestAnimationFrame(loop);